matrix:
- name: Check English
  sources:
  # - src/en/**/*.md
    - src/en/**/*.md
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - dictionary/en/wordlist.txt
    output: dictionary/en/en.dic
  pipeline:
    - pyspelling.filters.markdown:
